stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  image: node:dubnium
  script:
    - npm ci
    - npm run prettier:check

test:dubnium:
  stage: test
  image: node:dubnium
  script:
    - npm i -g @vue/cli
    - cwd=$(pwd)
    - cd /
    - vue create --preset "$cwd/test-preset.json" $projectName
    - cd $projectName
    - npm install "$cwd"
    - vue invoke @webqam/vue-cli-plugin-sass-boilerplate
  variables:
    projectName: test-vue
