stages:
  - lint
  - test
  - publish

lint:
  stage: lint
  image: node:dubnium
  script:
    - npm ci
    - npm run prettier:check

test:dubnium:
  stage: test
  image: node:dubnium
  script:
    - npm i -g @vue/cli
    - cwd=$(pwd)
    - cd /
    - vue create --preset "$cwd/test-preset.json" $projectName
    - cd $projectName
    - npm install "$cwd"
    - vue invoke @webqam/vue-cli-plugin-sass-boilerplate
  variables:
    projectName: test-vue

publish:
  stage: publish
  image: node:dubnium
  script:
    - '[[ -z $NPM_TOKEN ]] && exit 1'
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - npm publish --access public
  only:
    - /^(0|[1-9]\d*)\.(0|[1-9≥]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  allow_failure: true
